baseURL = 'https://team-roadrash.github.io/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Embedded Systems'

## Site Settings
[params]
logo = "assets/img/logo1.png"
favicon = "assets/webicon.png"

# Info
address = "6N 42nd St, USA"
email = "surajsbm@seas.upenn.edu  koushik@seas.upenn.edu"
phone = "(929) 613-7802"

# Socials
github = "https://github.com/SurajMarthy1001"
github = "https://github.com/koushik-sss"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3